#simple IOS config in ansible
---
- name: Sample IOS show ntp for Ansible 2.5
  hosts: iosxe
  gather_facts: no

  tasks:

  - name: run show ntp config
    ios_command:
      commands: show ntp config
    register: myntp

  - debug: 
      var: myntp.stdout_lines[0]


